CREATE USER bv115 IDENTIFIED BY bv115 DEFAULT TABLESPACE MEDISOFT QUOTA 100M ON MEDISOFT;
GRANT CREATE SESSION, IMP_FULL_DATABASE TO bv115;
GRANT JAVASYSPRIV, JAVAUSERPRIV TO bv115;
GRANT ALL PRIVILEGES TO bv115;
alter user bv115 identified by bv115;
exit;